before_install:
  - npm update
cache: npm
branches:
  only:
    - master
install:
  - npm install
language: node_js
node_js:
  - node
script:
  - npm run build
  - npx codechecks
  - npm run coverage
sudo: false
deploy:
  provider: npm
  email: lewis-gibson@hotmail.com
  api_key:
    secure: rlxm8QYa6/4R0XaLTalHN+w+H1AIbUdSYh+sTUyq1rQnCQVhuhCOjGzhI/XbkYi3lshg57Wc23sx4Nasr1sGWBAQiQaC+5Ou/BwfYF11XVAD9c5IpDc48G/6CqAsc39NdmrRPl6AIFAL8Y58qzsdYD5r+Sg0mEHP3qnDOqzsMnXnk6TwRbflpvw8QMbJV5Gvlgf+6EOF4Z5bYyhIcy6XPT1lsS4ROVstb9aPGitpSdlYQIyStLNq/jyi3X/Zx9+yEQgzSAIq53qCCbGN6nhFmpZRG4RSdWiOeHTdcIrlXy6ZPsM1qw5LuCkimOYoovMPlxn4EBt/Eew/7Q9pGHcNiNfMEfjqgOlZmHSTNKyepanK+gRS78GrokvysZarpA8TZcuvFLYdb/GZQrcvHUglEh6dMnaJpUxVFTRp+neflzD075AixByDXOhJ4mMoUSlkuEoPHhA/hPGLntd2RCBDGhA84qteb3MrZgCRKwlLkBbQj83RstCA7ovwZ4RKP6l/VXstnO6sb2nuVmUftyjyWtjj9q/yq73Utv0mOdXuthxsRO4LYszp9t3CR/+Op7KzwTK7SDuBxL6iJPer0wp3paQUWrYw9/Ix+owVbkDzySq7I+843MHm78cAOffncCxyGiev6U2HW+jokvlJyww4GF0Fvoa2YxauXWWC78SNth0=
  on:
    repo: Robinlemon/priority-concurrency-queue
